name: Execute From Shell Script


on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Exceute Shell Script
          run: |
            chmod +x shellscript.sh
            ./shellscript.sh
    
        - name: List Repo files
          run: ls -ltra
