name: Generate ASCII Artwork


on:
  push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: action/checkout@v4

        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay command
          run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt

        - name: Read File
          run: cat dragon.txt

        - name: List Repo files
          run: ls -ltra

